
### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Register
POST {{baseUrl}}/register
Content-Type: application/json
{
    "email": "",
    "password": ""
    "confirmPassword": ""

}

### Logout
POST {{baseUrl}}/logout

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Get user
GET {{baseUrl}}/user
Content-Type: application/json

### Get user links
GET {{baseUrl}}/links

### Get details of a link
GET {{baseUrl}}/links/:id

### Get links with range
GET {{baseUrl}}/links-range?skip=3&take=1


### Get links with stats
GET {{baseUrl}}/links-with-stats

### only for tests /redirect
GET {{baseUrl}}/redirect

### post link anon
POST {{baseUrl}}/link-anon

### post link
POST {{baseUrl}}/link-anon