FROM node:20-alpine

WORKDIR /app

ARG EXPRESS_DATABASE_URL
ARG EXPRESS_DIRECT_URL

ENV PORT=3000
ENV EXPRESS_DATABASE_URL=$EXPRESS_DATABASE_URL
ENV EXPRESS_DIRECT_URL=$EXPRESS_DIRECT_URL



RUN apk add --no-cache openssl

COPY prisma/ ./prisma/
COPY package*.json ./
RUN npm install


COPY . .
RUN npx prisma generate
RUN npx prisma db push
RUN npm run build



ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "build/src/index.js"]