name: Registry image to Docker Hub
on: [workflow_dispatch]
jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./express-backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/short-url-backend:latest-${{github.run_number}}
          build-args: |
            EXPRESS_DATABASE_URL=${{secrets.EXPRESS_DATABASE_URL}}
            EXPRESS_DIRECT_URL=${{secrets.EXPRESS_DIRECT_URL}}
