name: Deploy front to vercel

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

on: [workflow_dispatch]

jobs:
  vercel_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Change directory to front
        run: cd ./links-shortener

      - name: Install dependencies
        run: npm install
        working-directory: ./links-shortener

      - name: Build Vite app
        run: npm run build
        working-directory: ./links-shortener

      - name: Vercel install
        run: npm install -g vercel
      - name: Vercel Provide Envs
        run: vercel \
          --build-env VITE_FRONTEND_URL=${{ secrets.VITE_FRONTEND_URL }} \
          --build-env VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} \
          --build-env VITE_DB_ENDPOINT=${{ secrets.VITE_DB_ENDPOINT }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./links-shortener
      - name: Deploy Project Artifacts
        run:
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} \
          --env VITE_FRONTEND_URL=${{ secrets.VITE_FRONTEND_URL }} \
          --env VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} \
          --env VITE_DB_ENDPOINT=${{ secrets.VITE_DB_ENDPOINT }}
